name    = MCP-Wiki
author  = Torsten Raudssus <getty@cpan.org>
license = Perl_5
copyright_holder = Torsten Raudssus <torsten@raudssus.de> L<https://raudssus.de/>
copyright_year   = 2026
main_module     = lib/MCP/Wiki.pm

; Getty release command:
;   dzil release

[@Author::GETTY]
docker_image = localhost:5000/mcp-wiki
docker_build = latest
docker_local = 1  ; Tag locally, never push